# Generated by Django 3.2.8 on 2021-10-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('slug', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('asi_desc', models.TextField()),
                ('asi', models.TextField()),
                ('age', models.TextField()),
                ('alignment', models.TextField()),
                ('size', models.TextField()),
                ('speed', models.TextField()),
                ('speed_desc', models.TextField()),
                ('languages', models.TextField()),
                ('vision', models.TextField()),
                ('traits', models.TextField()),
                ('subraces', models.TextField()),
                ('document_slug', models.CharField(max_length=40)),
                ('document_title', models.CharField(max_length=40)),
                ('document_license_url', models.CharField(max_length=40)),
            ],
        ),
    ]
