# Generated by Django 3.2.8 on 2021-10-28 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('race', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Race',
        ),
    ]
