# Generated by Django 3.2.8 on 2021-11-08 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charSheet', '0002_auto_20211028_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='playerClass',
            field=models.CharField(default=None, max_length=30),
            preserve_default=False,
        ),
    ]
